[package]
name = "fly-sim-server"
version = "0.1.0"
edition = "2021"

[dependencies]
fly-sim-core = { path = "../fly-sim-core" }
flyctrl-core = { path = "../../../mcu/oop/flyctrl/core" }
phy-sdk = { path = "../../../game/physics/crates/phy-sdk" }
phy-rigid = { path = "../../../game/physics/crates/phy-rigid" }
phy-math = { path = "../../../game/physics/crates/phy-math" }
phy-demo = { path = "../../../game/physics/crates/phy-demo" }

[profile.release]
opt-level = 3
